### PR TITLE
Add claims support

### PR DESCRIPTION
**Pull request by mlynch**
Adds support for the `claims` field in the latest version of the `ADAL` library.

### CODE REVIEW

**Comment by mlynch** [comment]
cc @leewhitbeck. Want to give this a try? It should work now with the extra `claims` field. It was named something slightly different in the new version of the plugin.

Also, to reinstall the plugin, make sure you remove references to it from everywhere, including `package.json`, `package-lock.json`, and `node_modules`. It's a known issue in Cordova we are hoping to get fixed

**Comment by leewhitbeck** [comment]
@mlynch I will give it a whirl now. Thanks!

**Comment by leewhitbeck** [comment]
hey @mlynch, I am getting the below error when I try to compile.

Note:
I tried installing off the wip-claims branch, but that didn't work for me.
cordova plugin add https://github.com/mlynch/azure-activedirectory-library-for-cordova.git#wip-claims

I downloaded the wip-claims branch src and installing from that directory - that seemed to bring it in.
cordova plugin add ~/my  wip-claims install location

 error coming from /platforms/ios/@RTI/Plugins/cordova-plugin-ms-adal/CordovaAdalPlugin.m

> No visible @interface for 'ADAuthenticationContext' declares the selector 'acquireTokenWithResource:clientId:redirectUri:promptBehavior:userIdentifier:extraQueryParameters:claims:extraQueryParameters:completionBlock:'

Let me know if it would help to set up a screen share

**Comment by mlynch** [comment]
Ah seeing that now on fresh install. Must have missed something

**Comment by mlynch** [comment]
Fixed! Try now. Had a duplicated line

**Comment by leewhitbeck** [comment]
Thanks, that did the trick! Xcode logs showing that the claims are being accepted. Looks like the issue is still happening, but at least we are hitting the latest ios adal library- I'll have to wade through the logs some more. I really appreciate the help.

**Review by leewhitbeck — APPROVED** [review]

**Comment by mlynch** [comment]
Awesome. Standing by for more info

**Comment by leewhitbeck** [comment]
Hey @mlynch , looks like it is working! I was sending the claims info in the wrong format.  Thanks so much for the help with this. Can we merge this into master?

**Comment by mlynch** [comment]
@leewhitbeck awesome. Merged!

**Pull request merged**
